views/tokens_bp.py
#coding:utf-8
from flask import Blueprint, request, render_template, redirect, flash
from mongokit import ObjectId

from models import db, Sentence, Token
from _views import get_reference_tokens, require_admin, query_page
from settings import COURSE_LIST, FLAW_LIST

bp = Blueprint('tokens', __name__)


def query_sidebar_info(request):
    course = request.args.get('course', 'ALL')
    flaw = request.args.get('flaw', 'ALL')
    no_trash = request.args.get('no_trash', '1')
    page = int(request.args.get('page', 1))
    count = int(request.args.get('count', 15))
    search_word = request.args.get('search_word', '')

    print flaw

    query = []

    if course != 'ALL':
        query.append({'courses': course})

    if flaw == 'NO_EXPLAIN':
        query.append({'exp.cn': []})
    elif flaw == 'NO_CORE':
        query.append({'exp.core': {'$in': [None, u'']}})
    elif flaw == 'WORD':
        query.append({'tags': u'word'})
    elif flaw == 'PHRASE':
        query.append({'tags': u'phrase'})

    if no_trash != '0':
        query.append({'tags': {'$ne': u'trash'}})

    if search_word:
        query.append({'hash': Token.make_hash(search_word)})


    if query:
        full_query = {'$and': query}
    else:
        full_query = {}

    print 'query', query
    print 'full_query', full_query
    token_list, pager = query_page(db.Token, full_query, [('hash', 1)], page, count)

    return {
        'course_list': COURSE_LIST,
        'flaw_list': FLAW_LIST,
        'token_list': token_list,
        'pager': pager,
        'search_word': search_word,
        }



@bp.route('', methods=['GET'])
@require_admin
def view_token():
    page_info = query_sidebar_info(request)
    search_word = request.args.get('search_word', '').strip()
    token_id = request.args.get('token_id')
    mode = request.args.get('mode', 'edit')

    if search_word and page_info['pager']['total'] > 0 and page_info['token_list']:
        token = page_info['token_list'][0]
    elif token_id and token_id != 'None':
        token = db.Token.find_one(ObjectId(token_id))
        if not token:
            token = page_info['token_list'][0]
    else:
        token = page_info['token_list'][0]

    reference_tokens = get_reference_tokens(token.en)

    return render_template(
        'tokens.html',
        mode = mode,
        page_info = page_info,
        token = token,
        sentence_list = Sentence.get_token_sentences(token),
        references_tokens = reference_tokens,
    )


@bp.route('', methods=['POST'])
@require_admin
def save_token():
    en = request.form.get('en', '').strip()
    token_id = request.form.get('id')
    exp_core = request.form.get('exp_core')
    courses = [ x.strip() for x in request.form.getlist('course') if x ]
    note = request.form.get('note').strip()
    is_trash = request.form.get('is_trash')

    if token_id:
        token = db.Token.find_one(ObjectId(token_id))
        if token:
            if en and token.en != en:
                token.en = en

            token.courses = set(courses)
            token.note = note
            token.exp.core = exp_core
            if is_trash:
                token.trash(True)
            else:
                token.trash(False)
            token.save()
    flash(u'已成功保存', 'alert-success')
    return redirect(request.headers.get('referer'))

templates/core_exp_list.html
{% extends "layout.html" %}

{% block main %}

{% from 'macros.html' import pagination %}

<div id="coreexp-list-page" class="container ">

    <ul class="nav nav-pills pull-left">
        <li {% if request.args.channel == 'open' %}class="active"{% endif %}>
            <a href="javascript:change_param('channel', 'open')">开放</a>
        </li>
        <li {% if request.args.channel == 'closed' %}class="active"{% endif %}>
            <a href="javascript:change_param('channel', 'closed')">已关闭</a>
        </li>
        <li {% if request.args.channel == 'all' or not request.args.channel %}class="active"{% endif %}>
            <a href="javascript:change_param('channel', 'all')">全部</a>
        </li>
        <!--li {% if request.args.channel == 'auto_close' %}class="active"{% endif %}>
        <a href="javascript:change_param('channel', 'auto_close')">自动关闭候选</a>
        </li-->
    </ul>

    <div class="pull-right">{{ pagination( pager.current, pager.total ) }}</div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    单词
                </th>
                <th>
                    结果
                    <a id="auto-close-button" href="{{url_for('.auto_close')}}" class="pull-right">自动关闭</a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for ce in ce_list %}
            <tr>
                <td class="en">
                    <h3 title="{{ce.log_html}}">{{ce.en}}</h3>
                    <span class="label {% if 'closed' in ce.tags %}label-success{% endif %}"
                          data-id="{{ce._id}}"
                          data-tag="closed"
                    >关闭</span>
                </td>
                <td class="answer">
                    <ul>
                    {% for option in ce.ordered_options %}
                        <li>
                            <p>
                                <span class="cn">{{option.cn}}</span>

                                <a href="javascript:" {% if option.tag == 'best' %} class="tagged" {% endif %}
                                   data-option="{{option.cn}}" data-tag="best" data-id="{{ce._id}}">最佳</a>
                                <a href="javascript:" {% if option.tag == 'bad' %} class="tagged" {% endif %}
                                   data-option="{{option.cn}}" data-tag="bad" data-id="{{ce._id}}">最差</a>
                                <a href="javascript:"
                                data-option="{{option.cn}}" data-tag="" data-id="{{ce._id}}">None</a>
                            </p><br/>
                            <span class="label label-warning {{option.tag}}" style="width:{{option.voters|length * 10}}px">{{option.voters | length }}</span>
                            <p class="voters">【{{option.editor}}】{{option.voters | join(', ')}}</p>
                        </li>
                    {% endfor %}
                    </ul>
                    <p class="skippers">{{ce.skippers | join(', ')}}</p>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="pull-right">{{ pagination( pager.current, pager.total ) }}</div>

</div><!--/.container-->

{% endblock %}


{% block bottom %}
<script type="text/javascript" src="/static/js/coreexp-list.js"></script>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">

    <title>DictManager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="/static/img/icons/favicon.ico">

    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style> body { padding-top: 60px; } </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="/static/js/libs/html5.js" type="text/javascript"></script>
    <![endif]-->

    <link href="/static/css/base.less" rel="stylesheet/less" />
    <script src="/static/js/libs/less-1.1.3.min.js" type="text/javascript"></script>

    <script src="http://127.0.0.1:9555/con/assets/js/f5.js"></script>
</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar pull-right" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>

            <a class="brand" href="/">DictManager</a>
            <span class="user-name pull-left">{{session.name}}</span>

            <div class="nav-collapse">
                <ul class="nav pull-right">
                    {% if session.role == 'admin' %}<li><a href="{{ url_for('tokens.view_token') }}">单词列表</a></li>{% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% block main %}{% endblock %}


<script src="/static/js/libs/jquery-1.7.1.min.js" type="text/javascript"></script>
<script src="/static/js/libs/bootstrap/bootstrap.js" type="text/javascript"></script>

<script src="/static/js/libs/mustache.js" type="text/javascript"></script>
<script src="/static/js/libs/underscore.js" type="text/javascript"></script>
<script src="/static/js/libs/backbone.js" type="text/javascript"></script>
<script src="/static/js/libs/url.js" type="text/javascript"></script>
<script src="/static/js/libs/jquery.placeholder.min.js" type="text/javascript"></script>

<script src="/static/js/sidebar.js" type="text/javascript"></script>
<script src="/static/js/base.js" type="text/javascript"></script>
<script src="/static/js/utils.js" type="text/javascript"></script>

{% block bottom %}{% endblock %}

</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block main %}
<div id="login-page" class="container "><div class="row">
    <div class="span3">&nbsp;</div>

    <div class="span6">
        <form id="login" class="form-horizontal" method="POST" action="/login">
            <fieldset>
                <div class="control-group" id="info">
                    <label class="control-label"></label>
                    <div class="controls">
                        新用户 输入用户名和密码直接注册登录
                    </div>
                </div>
                <div class="control-group" id="foreign">
                    <label class="control-label">用户名</label>
                    <div class="controls">
                        <input class="input-xlarge" name="name" value="">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label">密码</label>

                    <div class="controls">
                        <input type="password" class="input-xlarge" name="password" value="">
                    </div>
                </div>

                <div class="control-group">
                    <label class="control-label"></label>

                    <div class="controls">
                        <button type="submit" class="btn btn-primary">
                            <i class="icon-ok icon-white"></i>
                            登录
                        </button>
                    </div>
                </div>
            </fieldset>


        </form>
    </div>

    <div class="span3">&nbsp;</div>
</div></div>


{% endblock %}



{% block bottom %}
<script type="text/javascript" src="/static/js/login.js"></script>
{% endblock %}

templates/macros.html
{% macro pagination(current_page, total_page) %}
<div class="pagination">
    <ul>
        <li class="prev"><a href="javascript:change_page(1)">1</a></li>
        <li><a href="javascript:change_page({{[1,current_page-1]|max}})">&larr;</a></li>
        <li class="disabled"><a>{{current_page}}</a></li>
        <li><a href="javascript:change_page({{[total_page,current_page+1]|min}})">&rarr;</a></li>
        <li class="next"><a href="javascript:change_page({{total_page}})">{{total_page}}</a></li>
    </ul>
</div>
{% endmacro %}

{% macro references_table(reference_tokens) %}
<table class="table">
    <thead>
    <tr>
        <th>参考含义</th>
        <th>源</th>
    </tr>
    </thead>
    <tbody>
    {% for ref in reference_tokens %}
    <tr>
        <td>{{ref.exp|safe}}</td>
        <td>{{ref.src|safe}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% endmacro %}

{% macro alerts() %}
    {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
    {% for alert_class, message in messages %}
    <div class="alert {{alert_class}}">
        {{message}}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
{% endmacro %}

templates/sentences.html
{% extends "layout.html" %}

{% block main %}

<form id="sentences_form" class="form-horizontal" method="POST" action="/sentences">
    <fieldset>
        <input type="hidden" name="token_id" value="{{token._id}}">
        <input type="hidden" name="course" value="{{course}}">
        <h2>
            {% set foreign = token.foreign %}
            “{{foreign}}”的例句
            <small>{{ course }}</small></h2>
        <table class="table">
            {% for sentence in sentences %}
            <tr {#{% if banned %}class="banned"{% endif %} #}>
                <td>
                    {#
                    {% set btn_class = '' %}
                    {% set banned_courses = sentence.get_banned_courses(foreign) %}
                    {% if banned_courses|length ==0 %}
                        {% set btn_class = 'btn-success' %}
                    {% endif %}
                    <a href="javascript:void(0)" class="all btn btn-small {{btn_class}}">ALL</a>
                    #}
                </td>
                <td>
                    <input type="hidden" name="sentence_id" value="{{sentence._id}}">
                    <b>{{sentence.foreign}}</b><br/>
                    <span>{{sentence.chinese}}</span><br/>
                    {#
                    {% for _course in sidebar.course_list %}
                    {% set btn_class = '' %}
                        {% if not sentence.is_banned(foreign, _course) %}
                            {% set btn_class = 'btn-success' %}
                        {% endif %}
                        {% set btn_size = 'btn-mini' %}
                        {% if _course == course %}
                            {% set btn_size = 'btn' %}
                        {% endif %}
                        <a href="javascript:void(0)" class="course btn {{btn_size}} {{btn_class}}">{{_course}}</a>
                    {% endfor %}
                    #}
                </td>
            </tr>
            {% else %}
            <h1>没有例句</h1>
            {% endfor %}
        </table>


    </fieldset>

    <!--<div class="form-actions">-->
        <!--<button type="submit" class="btn btn-primary btn-large">-->
            <!--<i class="icon-ok icon-white"></i>-->
            <!--保存-->
        <!--</button>-->
    <!--</div>-->

</form>
{% endblock %}

{% block bottom %}
<script type="text/javascript" src="/static/js/sentences.js"></script>
{% endblock %}

templates/sidebar.html
<select class="span1" name="course_select" id="course_select">
    <option>ALL</option>
    {% for course in page_info.course_list %}
    <option>{{course}}</option>
    {% endfor %}
</select>

<select class="span2" name="flaw_select" id="flaw_select">
    <option>ALL</option>
    {% for flaw in page_info.flaw_list %}
    <option>{{flaw}}</option>
    {% endfor %}
</select>

<input id="no_trash" name="no_trash" type="checkbox" checked>

<input id="search_word" value="{{search_word}}" class="span3">

<ul id="token_list" class="unstyled">
    {% for _token in page_info.token_list %}
        {% if _token.en == token.en %}
    <li class="active">
        {% else %}
    <li>
        {% endif %}
        <a href="javascript:change_param('token_id', '{{_token._id}}')"
            {%if _token.is_trash%}disabled{%endif%}
        >{{_token.en}}</a>
    </li>
    {% endfor %}
</ul>

{% from 'macros.html' import pagination %}
{{ pagination( page_info.pager.current, page_info.pager.total ) }}




templates/starter-template.htm
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>DictManager</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <style> body { padding-top: 60px; } </style>
    <link href="/static/css/bootstrap-responsive.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="/static/js/libs/html5.js" type="text/javascript"></script>
    <![endif]-->

    <link rel="shortcut icon" href="/static/img/ico/favicon.ico">
</head>

<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">Project name</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li class="active"><a href="#Home">Home</a></li>
                    <li><a href="#About">About</a></li>
                    <li><a href="#Contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">

    <h1>Bootstrap starter template</h1>
    <p>Use this document as a way to quick start any new project.<br> All you get is this message and a barebones HTML document.</p>

</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="/static/js/libs/jquery-1.7.1.min.js"></script>
<script src="/static/js/libs/bootstrap/bootstrap.min.js"></script>
</body>
</html>

templates/tokens-editform.html
<form id="token_detail" class="form-horizontal" method="POST" action="/tokens">
    <fieldset>
        <input type="hidden" name="id" value="{{token._id}}">

        <div id="foreign" class="control-group">
            <label class="control-label">英文</label>
            <div class="controls">
                <input class="input-xlarge" name="en" value="{{token.en}}">
                <small style="color: grey;">{{ token.phs | join(';') }}</small>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">核心解释</label>
            <div class="controls">
                <input type='text' name="exp_core" value="{{token.exp.core}}" class="input-xlarge"
                       placeholder="要求：最核心最精简的词性和含义">
                <small style="color: grey;"></small>
            </div>
        </div>

        <div id="courses" class="control-group">
            <label class="control-label">课程</label>
            <div class="controls">
                {% for course_name in token.courses %}
                <input name="course" value="{{course_name}}" class="input-mini">
                {% else %}
                <input name="course" value="" class="input-mini">
                {% endfor %}
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">备注</label>
            <div class="controls">
                <textarea name="note" class="input-xlarge">{{token.note|default("", true)}}</textarea>
            </div>
        </div>

        <div id="trash" class="control-group">
            <label class="control-label"></label>

            <div class="controls">
                <label class="checkbox">
                    <input name="is_trash" type="checkbox" {% if 'trash' in token.tags %}checked{% endif %}>
                    垃圾箱
                </label>
            </div>
        </div>

        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn btn-primary">
                    <i class="icon-ok icon-white"></i>
                    保存
                </button>
            </div>
        </div>


    </fieldset>

</form>

templates/tokens-preview.html
<div class="token-preview">
    {% if token.phs %}
    <span class="ph">[ {{ token.phs | join(';') }} ]</span>
    {% endif %}
    <h2 class="en">{{ token.en }}</h2>
    <h2 class="cn">{{ token.exp.core }}</h2>
    {% set sentences = token.sentences() %}
    {% if sentences|length > 0 %}
    <p class="sentence en"> {{ sentences[0].en }} </p>
    <p class="sentence cn"> {{ sentences[0].cn }} </p>
    {% endif %}

    <h4>详细解释</h4>
</div>

templates/tokens.html
{% extends "layout.html" %}

{% block main %}
<div id="tokens-page" class="container"><div class="row">

    <div class="span3 sidebar">{% include 'sidebar.html' %}</div>

    <div class="span9">
        {% from 'macros.html' import alerts, references_table %}
        {{ alerts() }}

        <ul class="nav nav-tabs">
            <li {%if mode=='edit'%}class="active"{%endif%}>
                <a href="javascript:change_param('mode', 'edit')">编辑</a>
            </li>
            <li {%if mode=='preview'%}class="active"{%endif%}>
                <a href="javascript:change_param('mode', 'preview')">预览</a>
            </li>
        </ul>

        <div class="tab-content">
            <div class="tab-pane{% if mode=="edit" %} active {% endif %}" id="edit-pane">
                {% include  "tokens-editform.html" %}
            </div>


            <div class="tab-pane{% if mode=="preview" %} active {% endif %}" id="preview-pane">
                {% include "tokens-preview.html" %}
            </div>

        </div>




    </div><!--/.span9-->
</div></div>
{% endblock %}



{% block bottom %}
{% raw %}
<script type="text/html" id="_foreign_input">
    <li>
        <input class="input-xlarge" name="foreign.text" value="">
        <input class="input-mini" name="foreign.type" value="">
    </li>
</script>

<script type="text/html" id="_chinese_li">
    <li>
        <input name="chinese.POSs" value="" class="input-small" placeholder="词性（空）">
        <input name="chinese.text" value="" class="input-xlarge" placeholder="含义（空）">
    </li>
</script>

<script type="text/html" id="_freq_ngram_table_tr">
    {{#freq_list}}
    <tr>
        <td class="freq">{{count}}</td>
        <td class="ngram">{{ngram}}</td>
        <td><input type="checkbox"></td>
    </tr>
    {{/freq_list}}
</script>

<script type="text/html" id="_freq_20k_table_tr">
    {{#freq_list}}
    <tr>
        <td class="freq"><a href="javascript:void(0)">{{count}}</a></td>
        <td class="word">{{word}}</td>
    </tr>
    {{/freq_list}}
</script>

<script type="text/html" id="_course_input">
    <input name="course" value="" class="input-mini">
</script>
{% endraw %}

<script type="text/javascript" src="/static/js/tokens.js"></script>
{% endblock %}